/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedApontamentosRouteImport } from './routes/_authenticated/apontamentos'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedBalanceteRouteImport } from './routes/_authenticated/balancete'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDemonstrativosRouteImport } from './routes/_authenticated/demonstrativos'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedPeriodosRouteImport } from './routes/_authenticated/periodos'
import { Route as AuthenticatedPlanoDeContasRouteImport } from './routes/_authenticated/plano-de-contas'
import { Route as AuthenticatedReclassificacoesRouteImport } from './routes/_authenticated/reclassificacoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/_admin/usuarios'
import { Route as AuthenticatedAgentesIndexRouteImport } from './routes/_authenticated/agentes/index'
import { Route as ApiAgentsChatRouteImport } from './routes/api/agents/chat'
import { Route as ApiPublicHooksNightlyDailyRefreshRouteImport } from './routes/api/public/hooks/nightly-daily-refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApontamentosRoute =
  AuthenticatedApontamentosRouteImport.update({
    id: '/apontamentos',
    path: '/apontamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBalanceteRoute = AuthenticatedBalanceteRouteImport.update({
  id: '/balancete',
  path: '/balancete',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemonstrativosRoute =
  AuthenticatedDemonstrativosRouteImport.update({
    id: '/demonstrativos',
    path: '/demonstrativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeriodosRoute = AuthenticatedPeriodosRouteImport.update({
  id: '/periodos',
  path: '/periodos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoDeContasRoute =
  AuthenticatedPlanoDeContasRouteImport.update({
    id: '/plano-de-contas',
    path: '/plano-de-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReclassificacoesRoute =
  AuthenticatedReclassificacoesRouteImport.update({
    id: '/reclassificacoes',
    path: '/reclassificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAgentesIndexRoute =
  AuthenticatedAgentesIndexRouteImport.update({
    id: '/agentes/',
    path: '/agentes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAgentsChatRoute = ApiAgentsChatRouteImport.update({
  id: '/api/agents/chat',
  path: '/api/agents/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNightlyDailyRefreshRoute =
  ApiPublicHooksNightlyDailyRefreshRouteImport.update({
    id: '/api/public/hooks/nightly-daily-refresh',
    path: '/api/public/hooks/nightly-daily-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/balancete': typeof AuthenticatedBalanceteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demonstrativos': typeof AuthenticatedDemonstrativosRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/plano-de-contas': typeof AuthenticatedPlanoDeContasRoute
  '/reclassificacoes': typeof AuthenticatedReclassificacoesRoute
  '/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
  '/agentes/': typeof AuthenticatedAgentesIndexRoute
  '/api/public/hooks/nightly-daily-refresh': typeof ApiPublicHooksNightlyDailyRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/apontamentos': typeof AuthenticatedApontamentosRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/balancete': typeof AuthenticatedBalanceteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demonstrativos': typeof AuthenticatedDemonstrativosRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/periodos': typeof AuthenticatedPeriodosRoute
  '/plano-de-contas': typeof AuthenticatedPlanoDeContasRoute
  '/reclassificacoes': typeof AuthenticatedReclassificacoesRoute
  '/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
  '/agentes': typeof AuthenticatedAgentesIndexRoute
  '/api/public/hooks/nightly-daily-refresh': typeof ApiPublicHooksNightlyDailyRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/definir-senha': typeof DefinirSenhaRoute
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/apontamentos': typeof AuthenticatedApontamentosRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/balancete': typeof AuthenticatedBalanceteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demonstrativos': typeof AuthenticatedDemonstrativosRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/periodos': typeof AuthenticatedPeriodosRoute
  '/_authenticated/plano-de-contas': typeof AuthenticatedPlanoDeContasRoute
  '/_authenticated/reclassificacoes': typeof AuthenticatedReclassificacoesRoute
  '/_authenticated/_admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/agents/chat': typeof ApiAgentsChatRoute
  '/_authenticated/agentes/': typeof AuthenticatedAgentesIndexRoute
  '/api/public/hooks/nightly-daily-refresh': typeof ApiPublicHooksNightlyDailyRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/apontamentos'
    | '/atualizacoes'
    | '/balancete'
    | '/dashboard'
    | '/demonstrativos'
    | '/importar'
    | '/periodos'
    | '/plano-de-contas'
    | '/reclassificacoes'
    | '/usuarios'
    | '/api/agents/chat'
    | '/agentes/'
    | '/api/public/hooks/nightly-daily-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definir-senha'
    | '/login'
    | '/apontamentos'
    | '/atualizacoes'
    | '/balancete'
    | '/dashboard'
    | '/demonstrativos'
    | '/importar'
    | '/periodos'
    | '/plano-de-contas'
    | '/reclassificacoes'
    | '/usuarios'
    | '/api/agents/chat'
    | '/agentes'
    | '/api/public/hooks/nightly-daily-refresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/definir-senha'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/apontamentos'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/balancete'
    | '/_authenticated/dashboard'
    | '/_authenticated/demonstrativos'
    | '/_authenticated/importar'
    | '/_authenticated/periodos'
    | '/_authenticated/plano-de-contas'
    | '/_authenticated/reclassificacoes'
    | '/_authenticated/_admin/usuarios'
    | '/api/agents/chat'
    | '/_authenticated/agentes/'
    | '/api/public/hooks/nightly-daily-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  LoginRoute: typeof LoginRoute
  ApiAgentsChatRoute: typeof ApiAgentsChatRoute
  ApiPublicHooksNightlyDailyRefreshRoute: typeof ApiPublicHooksNightlyDailyRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apontamentos': {
      id: '/_authenticated/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof AuthenticatedApontamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balancete': {
      id: '/_authenticated/balancete'
      path: '/balancete'
      fullPath: '/balancete'
      preLoaderRoute: typeof AuthenticatedBalanceteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demonstrativos': {
      id: '/_authenticated/demonstrativos'
      path: '/demonstrativos'
      fullPath: '/demonstrativos'
      preLoaderRoute: typeof AuthenticatedDemonstrativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/periodos': {
      id: '/_authenticated/periodos'
      path: '/periodos'
      fullPath: '/periodos'
      preLoaderRoute: typeof AuthenticatedPeriodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-de-contas': {
      id: '/_authenticated/plano-de-contas'
      path: '/plano-de-contas'
      fullPath: '/plano-de-contas'
      preLoaderRoute: typeof AuthenticatedPlanoDeContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reclassificacoes': {
      id: '/_authenticated/reclassificacoes'
      path: '/reclassificacoes'
      fullPath: '/reclassificacoes'
      preLoaderRoute: typeof AuthenticatedReclassificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/usuarios': {
      id: '/_authenticated/_admin/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/agentes/': {
      id: '/_authenticated/agentes/'
      path: '/agentes'
      fullPath: '/agentes/'
      preLoaderRoute: typeof AuthenticatedAgentesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agents/chat': {
      id: '/api/agents/chat'
      path: '/api/agents/chat'
      fullPath: '/api/agents/chat'
      preLoaderRoute: typeof ApiAgentsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nightly-daily-refresh': {
      id: '/api/public/hooks/nightly-daily-refresh'
      path: '/api/public/hooks/nightly-daily-refresh'
      fullPath: '/api/public/hooks/nightly-daily-refresh'
      preLoaderRoute: typeof ApiPublicHooksNightlyDailyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedApontamentosRoute: typeof AuthenticatedApontamentosRoute
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedBalanceteRoute: typeof AuthenticatedBalanceteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemonstrativosRoute: typeof AuthenticatedDemonstrativosRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedPeriodosRoute: typeof AuthenticatedPeriodosRoute
  AuthenticatedPlanoDeContasRoute: typeof AuthenticatedPlanoDeContasRoute
  AuthenticatedReclassificacoesRoute: typeof AuthenticatedReclassificacoesRoute
  AuthenticatedAgentesIndexRoute: typeof AuthenticatedAgentesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedApontamentosRoute: AuthenticatedApontamentosRoute,
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedBalanceteRoute: AuthenticatedBalanceteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemonstrativosRoute: AuthenticatedDemonstrativosRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedPeriodosRoute: AuthenticatedPeriodosRoute,
  AuthenticatedPlanoDeContasRoute: AuthenticatedPlanoDeContasRoute,
  AuthenticatedReclassificacoesRoute: AuthenticatedReclassificacoesRoute,
  AuthenticatedAgentesIndexRoute: AuthenticatedAgentesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DefinirSenhaRoute: DefinirSenhaRoute,
  LoginRoute: LoginRoute,
  ApiAgentsChatRoute: ApiAgentsChatRoute,
  ApiPublicHooksNightlyDailyRefreshRoute:
    ApiPublicHooksNightlyDailyRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
